services:
  db:
    image: postgres
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_HOME}/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - ${NEXTCLOUD_HOME}/nextcloud:/var/www/html
      - ${NEXTCLOUD_HOME}/apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_HOME}/config:/var/www/html/config
      - ${NEXTCLOUD_HOME}/data:/var/www/html/data
      - ${NEXTCLOUD_HOME}/themes:/var/www/html/themes
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  db:
  nextcloud:

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username to this file
